export const CONVERSATION_RELATIONS = [
  { id: "first-meeting", label: "初めまして", description: "答えやすい話題から" },
  { id: "coworker", label: "同僚", description: "仕事の合間の自然な雑談" },
  { id: "boss", label: "上司", description: "経験やおすすめを聞く" },
  { id: "subordinate", label: "部下", description: "気軽に話せる空気をつくる" },
  { id: "parttime-student", label: "バイト先の学生", description: "学校や日常の話をやさしく" },
  { id: "parttime-part", label: "バイト先のパート", description: "休憩中にも話せる話題" },
  { id: "school-friend", label: "学校の友達", description: "授業や最近のことから" },
  { id: "teacher", label: "先生", description: "相談や経験を自然に聞く" },
  { id: "other", label: "その他", description: "場面に合わせて考える" },
  { id: "trivia", label: "雑学から探す", description: "小さな知識を会話の入口に" },
];

export const RELATION_HINTS = {
  "first-meeting": [
    { id: "first-arrival", prompt: "今日はここまで、どうやって来たんですか？", followUp: "この辺にはよく来られるんですか？", opener: "初めてだと少し緊張しますね。そういえば…", memo: "ここまでの道のりや、この辺に来ることがあるか聞いてみたい" },
    { id: "first-place", prompt: "この場所やイベントは、どうやって知ったんですか？", followUp: "参加してみようと思ったきっかけはありますか？", memo: "この場所やイベントを知ったきっかけについて聞いてみたい" },
    { id: "first-weekend", prompt: "休日は、どんなふうに過ごすことが多いですか？", followUp: "最近やってみて楽しかったことはありますか？", opener: "差し支えなければ、ちょっと聞いてみたいんですけど…", memo: "休日の過ごし方について聞いてみたい" },
    { id: "first-food", prompt: "この近くで、気になっているお店はありますか？", followUp: "好きな食べ物ってありますか？", memo: "近くのお店や好きな食べ物について聞いてみたい" },
  ],
  acquaintance: [
    { id: "acq-follow", prompt: "この前話していたこと、その後どうなりました？", followUp: "最近はどんな感じですか？", opener: "そういえば、前に話していたことを思い出して…", memo: "前に話していたことの続きを聞いてみたい" },
    { id: "acq-hobby", prompt: "最近、何かハマっているものありますか？", followUp: "始めたきっかけって何だったんですか？", memo: "最近ハマっているものについて聞いてみたい" },
    { id: "acq-recommend", prompt: "最近、人におすすめしたくなったものってありますか？", followUp: "どんなところがよかったですか？", memo: "最近おすすめしたくなったものについて聞いてみたい" },
    { id: "acq-small", prompt: "最近、ちょっと嬉しかったことってありました？", followUp: "それはいいですね。どんな場面だったんですか？", memo: "最近あった小さな嬉しいことについて聞いてみたい" },
  ],
  junior: [
    { id: "junior-settle", prompt: "最近、少し慣れてきた？", followUp: "やっていて面白いと思うことある？", opener: "無理に答えなくて大丈夫なんだけど…", memo: "最近慣れてきたことや面白いことを聞いてみたい" },
    { id: "junior-help", prompt: "今、困っていることとかない？", followUp: "自分でよければ、一緒に考えるよ。", memo: "困っていることがないか気軽に聞いてみたい" },
    { id: "junior-off", prompt: "休みの日って、何してることが多い？", followUp: "最近いちばん楽しかったのは何？", memo: "休みの日の過ごし方について聞いてみたい" },
    { id: "junior-rec", prompt: "最近おすすめのものある？", followUp: "どこが気に入ってる？", memo: "最近のおすすめについて聞いてみたい" },
  ],
  senior: [
    { id: "senior-start", prompt: "これって、最初の頃どうやって慣れましたか？", followUp: "慣れるまでに意識していたことはありますか？", opener: "少し聞いてみたかったんですが…", memo: "最初の頃にどうやって慣れたか聞いてみたい" },
    { id: "senior-shop", prompt: "最近おすすめのお店とかありますか？", followUp: "そこでよく頼むものはありますか？", memo: "最近おすすめのお店について聞いてみたい" },
    { id: "senior-memory", prompt: "今までで、特に印象に残っていることってありますか？", followUp: "どんなところが印象に残りましたか？", memo: "これまでで印象に残っていることを聞いてみたい" },
    { id: "senior-current", prompt: "最近、楽しみにしていることってありますか？", followUp: "始めたきっかけも聞いてみたいです。", memo: "最近楽しみにしていることについて聞いてみたい" },
  ],
  coworker: [
    { id: "work-weather", prompt: "今日はちょっと暑いですね。夏って好きですか？", followUp: "夏になると食べたくなるものってあります？", memo: "季節の好みや夏に食べたいものについて話したい" },
    { id: "work-lunch", prompt: "お昼って、いつもどこで食べてます？", followUp: "この辺でおすすめのお店ありますか？", memo: "職場の近くのランチやおすすめのお店について聞いてみたい" },
    { id: "work-after", prompt: "最近、仕事終わりに何かハマってることあります？", followUp: "始めてみて、どんなところがよかったですか？", memo: "仕事終わりにハマっていることについて聞いてみたい" },
    { id: "work-break", prompt: "休憩するとき、何を飲むことが多いですか？", followUp: "気分を切り替えたいときの定番ってあります？", memo: "休憩中の飲み物や気分転換について聞いてみたい" },
  ],
  reunion: [
    { id: "reunion-new", prompt: "最近、何か新しく始めたことある？", followUp: "始めてみてどうだった？", opener: "久しぶり。そういえば最近は…", memo: "最近新しく始めたことについて聞いてみたい" },
    { id: "reunion-fun", prompt: "最近いちばん楽しかったことって何？", followUp: "どんなところが楽しかった？", memo: "最近いちばん楽しかったことについて聞いてみたい" },
    { id: "reunion-change", prompt: "前に会ってから、何か変わったことあった？", followUp: "今はどんな感じ？", memo: "前に会ってから変わったことについて聞いてみたい" },
    { id: "reunion-next", prompt: "最近、どこか行ってみたいところある？", followUp: "そこでは何をしてみたい？", memo: "最近行ってみたい場所について聞いてみたい" },
  ],
  anyone: [
    { id: "any-food", prompt: "最近食べて、おいしかったものある？", followUp: "自分でも作ったりする？", memo: "最近食べておいしかったものについて聞いてみたい" },
    { id: "any-weekend", prompt: "次の休み、何をして過ごしたい？", followUp: "家でゆっくりするなら何をする？", memo: "次の休日の過ごし方について話したい" },
    { id: "any-music", prompt: "最近よく聴いている曲ってある？", followUp: "どんなときに聴きたくなる？", memo: "最近よく聴いている音楽について聞いてみたい" },
    { id: "any-buy", prompt: "最近買ってよかったものある？", followUp: "使ってみて、どこがよかった？", memo: "最近買ってよかったものについて聞いてみたい" },
    { id: "any-place", prompt: "今、行ってみたい場所ってある？", followUp: "そこで何をしてみたい？", memo: "今行ってみたい場所について聞いてみたい" },
    { id: "any-child", prompt: "子どもの頃、何が好きだった？", followUp: "今でも好きだったりする？", memo: "子どもの頃に好きだったものについて聞いてみたい" },
  ],
};

RELATION_HINTS.boss = RELATION_HINTS.senior;
RELATION_HINTS.subordinate = RELATION_HINTS.junior;
RELATION_HINTS["parttime-student"] = RELATION_HINTS.junior;
RELATION_HINTS["parttime-part"] = RELATION_HINTS.coworker;
RELATION_HINTS["school-friend"] = RELATION_HINTS.anyone;
RELATION_HINTS.teacher = RELATION_HINTS.senior;
RELATION_HINTS.other = RELATION_HINTS.anyone;

export const BUILT_IN_HINTS = [
  {
    id: "otter-kelp",
    category: "動物",
    text: "ラッコは休むとき、流されにくいよう海藻に体を巻き付けることがあります。",
    question: "水族館で、つい長く見てしまう生き物は？",
    memo: "水族館でつい長く見てしまう生き物について話したい",
    source: "Monterey Bay Aquarium",
    url: "https://www.montereybayaquarium.org/animals/animals-a-to-z/sea-otter",
    checkedAt: "2026年7月",
  },
  {
    id: "octopus-hearts",
    category: "動物",
    text: "タコには心臓が3つあります。2つはえらへ、1つは全身へ血液を送ります。",
    question: "不思議だと思う海の生き物は？",
    memo: "不思議だと思う海の生き物について聞きたい",
    source: "Smithsonian Ocean",
    url: "https://ocean.si.edu/ocean-life/invertebrates/octopuses-and-squids",
    checkedAt: "2026年7月",
  },
  {
    id: "banana-berry",
    category: "食べ物",
    text: "植物学の分類では、バナナはベリーの仲間。名前の印象とは少し違います。",
    question: "名前と実物の印象が違った食べ物はある？",
    memo: "名前の印象と違った食べ物について話したい",
    source: "Encyclopaedia Britannica",
    url: "https://www.britannica.com/science/berry-plant-reproductive-body",
    checkedAt: "2026年7月",
  },
  {
    id: "apple-float",
    category: "食べ物",
    text: "りんごは中に空気を多く含むため、水に浮きやすい果物です。",
    question: "秋になると食べたくなるものは？",
    memo: "秋になると食べたくなるものを聞きたい",
    source: "USDA",
    url: "https://snaped.fns.usda.gov/resources/nutrition-education-materials/seasonal-produce-guide/apples",
    checkedAt: "2026年7月",
  },
  {
    id: "rain-smell",
    category: "科学",
    text: "雨上がりの土のにおいは「ペトリコール」と呼ばれます。",
    question: "好きな天気のにおいはある？",
    memo: "好きな天気のにおいについて話したい",
    source: "CSIRO",
    url: "https://www.csiro.au/en/news/all/articles/2015/march/what-is-petrichor",
    checkedAt: "2026年7月",
  },
  {
    id: "moon-footprints",
    category: "科学",
    text: "月には風や雨がほとんどないため、宇宙飛行士の足跡は長く残ります。",
    question: "一度行ってみたい場所は地球のどこ？",
    memo: "一度行ってみたい場所について聞きたい",
    source: "NASA",
    url: "https://science.nasa.gov/moon/",
    checkedAt: "2026年7月",
  },
  {
    id: "snow-crystals",
    category: "季節",
    text: "雪の結晶は基本的に六角形。育つときの温度や湿度で形が変わります。",
    question: "冬にだけ楽しみにしていることは？",
    memo: "冬に楽しみにしていることについて話したい",
    source: "NOAA",
    url: "https://www.noaa.gov/jetstream/snow",
    checkedAt: "2026年7月",
  },
  {
    id: "cherry-weather",
    category: "季節",
    text: "桜の開花予想には、冬から春にかけての気温の変化が使われます。",
    question: "春を感じる小さな合図は？",
    memo: "春を感じる小さな合図について聞きたい",
    source: "気象庁",
    url: "https://www.jma.go.jp/jma/kishou/know/kurashi/sakura.html",
    checkedAt: "2026年7月",
  },
  {
    id: "pencil-graphite",
    category: "身近なもの",
    text: "鉛筆の芯に鉛は使われておらず、主に黒鉛と粘土でできています。",
    question: "つい集めたくなる文房具は？",
    memo: "つい集めたくなる文房具について話したい",
    source: "Smithsonian Institution",
    url: "https://www.si.edu/spotlight/pencils",
    checkedAt: "2026年7月",
  },
  {
    id: "velcro-burr",
    category: "身近なもの",
    text: "面ファスナーは、服に付いた植物の実を観察したことから着想されました。",
    question: "身近な発明で、よくできていると思うものは？",
    memo: "よくできていると思う身近な発明を聞きたい",
    source: "Smithsonian Magazine",
    url: "https://www.smithsonianmag.com/innovation/accidental-invention-velcro-180972197/",
    checkedAt: "2026年7月",
  },
  {
    id: "tea-temperature",
    category: "暮らし",
    text: "同じお茶でも、お湯の温度や時間で香りと味の出方が変わります。",
    question: "ほっとするときに飲みたいものは？",
    memo: "ほっとするときに飲みたいものを聞きたい",
    source: "農林水産省",
    url: "https://www.maff.go.jp/j/seisan/tokusan/cha/ocha.html",
    checkedAt: "2026年7月",
  },
  {
    id: "music-memory",
    category: "音楽",
    text: "音楽は、その曲をよく聴いていた時期の出来事や気持ちを思い出すきっかけになることがあります。",
    question: "聴くと思い出が浮かぶ曲ってある？",
    memo: "好きな音楽と思い出について話したい",
    source: "National Institutes of Health",
    url: "https://www.nih.gov/news-events/nih-research-matters/music-memory-emotion",
    checkedAt: "2026年7月",
  },
  {
    id: "kanji-kasa",
    category: "言葉",
    text: "「傘」という漢字には、人が屋根の下に集まっているように見える部分があります。",
    question: "形が好きな漢字はある？",
    memo: "形が好きな漢字について聞きたい",
    source: "文化庁",
    url: "https://www.bunka.go.jp/seisaku/kokugo_nihongo/kokugo_shisaku/",
    checkedAt: "2026年7月",
  },
  {
    id: "emoji-origin",
    category: "文化",
    text: "絵文字は日本で生まれ、いまでは世界中の文字コードに収録されています。",
    question: "よく使う絵文字をひとつ選ぶなら？",
    memo: "よく使う絵文字について話したい",
    source: "Unicode Consortium",
    url: "https://home.unicode.org/emoji/about-emoji/",
    checkedAt: "2026年7月",
  },
  {
    id: "postcard-history",
    category: "歴史",
    text: "日本で郵便はがきが発行されたのは、明治時代の1873年です。",
    question: "手紙やはがきを最後に書いたのはいつ？",
    memo: "手紙やはがきの思い出について聞きたい",
    source: "郵政博物館",
    url: "https://www.postalmuseum.jp/column/transition/postcard.html",
    checkedAt: "2026年7月",
  },
  {
    id: "tokyo-stations",
    category: "地域",
    text: "東京駅の赤れんが駅舎は、創建時の姿を大切にしながら復原されました。",
    question: "好きな駅や、思い出のある駅は？",
    memo: "好きな駅や思い出のある駅について話したい",
    source: "JR東日本",
    url: "https://www.jreast.co.jp/tokyostation/",
    checkedAt: "2026年7月",
  },
  {
    id: "library-order",
    category: "文化",
    text: "図書館の本の背にある数字は、似たテーマの本を近くに並べるための手がかりです。",
    question: "本屋や図書館で、最初に見る棚は？",
    memo: "本屋や図書館で最初に見る棚を聞きたい",
    source: "国立国会図書館",
    url: "https://www.ndl.go.jp/jp/data/catstandards/classification_subject/ndlc.html",
    checkedAt: "2026年7月",
  },
  {
    id: "cloud-weight",
    category: "科学",
    text: "雲は軽く見えますが、小さな水滴が集まってできています。",
    question: "空を見ていて、何に見えた雲があった？",
    memo: "何かに見えた雲について話したい",
    source: "NOAA",
    url: "https://www.noaa.gov/jetstream/clouds",
    checkedAt: "2026年7月",
  },
  {
    id: "cat-whiskers",
    category: "動物",
    text: "猫のひげは、狭い場所や周りの動きを感じ取る助けになります。",
    question: "動物のすごい感覚で、ひとつ欲しいのは？",
    memo: "欲しい動物の感覚について聞きたい",
    source: "Cornell Feline Health Center",
    url: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center",
    checkedAt: "2026年7月",
  },
  {
    id: "bread-holes",
    category: "食べ物",
    text: "パンの中の穴は、酵母などが生地の中で作ったガスがふくらんだ跡です。",
    question: "焼きたてで食べたいパンは？",
    memo: "焼きたてで食べたいパンについて話したい",
    source: "American Chemical Society",
    url: "https://www.acs.org/education/whatischemistry/adventures-in-chemistry/experiments/yeast-air-balloons.html",
    checkedAt: "2026年7月",
  },
];
