export const BUILT_IN_HINTS = [
  {
    id: "otter-kelp",
    category: "動物",
    text: "ラッコは休むとき、流されにくいよう海藻に体を巻き付けることがあります。",
    question: "水族館で、つい長く見てしまう生き物は？",
    source: "Monterey Bay Aquarium",
    url: "https://www.montereybayaquarium.org/animals/animals-a-to-z/sea-otter",
    checkedAt: "2026年7月",
  },
  {
    id: "octopus-hearts",
    category: "動物",
    text: "タコには心臓が3つあります。2つはえらへ、1つは全身へ血液を送ります。",
    question: "不思議だと思う海の生き物は？",
    source: "Smithsonian Ocean",
    url: "https://ocean.si.edu/ocean-life/invertebrates/octopuses-and-squids",
    checkedAt: "2026年7月",
  },
  {
    id: "banana-berry",
    category: "食べ物",
    text: "植物学の分類では、バナナはベリーの仲間。名前の印象とは少し違います。",
    question: "名前と実物の印象が違った食べ物はある？",
    source: "Encyclopaedia Britannica",
    url: "https://www.britannica.com/science/berry-plant-reproductive-body",
    checkedAt: "2026年7月",
  },
  {
    id: "apple-float",
    category: "食べ物",
    text: "りんごは中に空気を多く含むため、水に浮きやすい果物です。",
    question: "秋になると食べたくなるものは？",
    source: "USDA",
    url: "https://snaped.fns.usda.gov/resources/nutrition-education-materials/seasonal-produce-guide/apples",
    checkedAt: "2026年7月",
  },
  {
    id: "rain-smell",
    category: "科学",
    text: "雨上がりの土のにおいは「ペトリコール」と呼ばれます。",
    question: "好きな天気のにおいはある？",
    source: "CSIRO",
    url: "https://www.csiro.au/en/news/all/articles/2015/march/what-is-petrichor",
    checkedAt: "2026年7月",
  },
  {
    id: "moon-footprints",
    category: "科学",
    text: "月には風や雨がほとんどないため、宇宙飛行士の足跡は長く残ります。",
    question: "一度行ってみたい場所は地球のどこ？",
    source: "NASA",
    url: "https://science.nasa.gov/moon/",
    checkedAt: "2026年7月",
  },
  {
    id: "snow-crystals",
    category: "季節",
    text: "雪の結晶は基本的に六角形。育つときの温度や湿度で形が変わります。",
    question: "冬にだけ楽しみにしていることは？",
    source: "NOAA",
    url: "https://www.noaa.gov/jetstream/snow",
    checkedAt: "2026年7月",
  },
  {
    id: "cherry-weather",
    category: "季節",
    text: "桜の開花予想には、冬から春にかけての気温の変化が使われます。",
    question: "春を感じる小さな合図は？",
    source: "気象庁",
    url: "https://www.jma.go.jp/jma/kishou/know/kurashi/sakura.html",
    checkedAt: "2026年7月",
  },
  {
    id: "pencil-graphite",
    category: "身近なもの",
    text: "鉛筆の芯に鉛は使われておらず、主に黒鉛と粘土でできています。",
    question: "つい集めたくなる文房具は？",
    source: "Smithsonian Institution",
    url: "https://www.si.edu/spotlight/pencils",
    checkedAt: "2026年7月",
  },
  {
    id: "velcro-burr",
    category: "身近なもの",
    text: "面ファスナーは、服に付いた植物の実を観察したことから着想されました。",
    question: "身近な発明で、よくできていると思うものは？",
    source: "Smithsonian Magazine",
    url: "https://www.smithsonianmag.com/innovation/accidental-invention-velcro-180972197/",
    checkedAt: "2026年7月",
  },
  {
    id: "tea-temperature",
    category: "暮らし",
    text: "同じお茶でも、お湯の温度や時間で香りと味の出方が変わります。",
    question: "ほっとするときに飲みたいものは？",
    source: "農林水産省",
    url: "https://www.maff.go.jp/j/seisan/tokusan/cha/ocha.html",
    checkedAt: "2026年7月",
  },
  {
    id: "sleep-cycles",
    category: "暮らし",
    text: "眠りは一晩中同じ深さではなく、いくつかの段階を繰り返します。",
    question: "よく眠れた朝にしたいことは？",
    source: "NIH",
    url: "https://www.nhlbi.nih.gov/health/sleep/stages-of-sleep",
    checkedAt: "2026年7月",
  },
  {
    id: "kanji-kasa",
    category: "言葉",
    text: "「傘」という漢字には、人が屋根の下に集まっているように見える部分があります。",
    question: "形が好きな漢字はある？",
    source: "文化庁",
    url: "https://www.bunka.go.jp/seisaku/kokugo_nihongo/kokugo_shisaku/",
    checkedAt: "2026年7月",
  },
  {
    id: "emoji-origin",
    category: "文化",
    text: "絵文字は日本で生まれ、いまでは世界中の文字コードに収録されています。",
    question: "よく使う絵文字をひとつ選ぶなら？",
    source: "Unicode Consortium",
    url: "https://home.unicode.org/emoji/about-emoji/",
    checkedAt: "2026年7月",
  },
  {
    id: "postcard-history",
    category: "歴史",
    text: "日本で郵便はがきが発行されたのは、明治時代の1873年です。",
    question: "手紙やはがきを最後に書いたのはいつ？",
    source: "郵政博物館",
    url: "https://www.postalmuseum.jp/column/transition/postcard.html",
    checkedAt: "2026年7月",
  },
  {
    id: "tokyo-stations",
    category: "地域",
    text: "東京駅の赤れんが駅舎は、創建時の姿を大切にしながら復原されました。",
    question: "好きな駅や、思い出のある駅は？",
    source: "JR東日本",
    url: "https://www.jreast.co.jp/tokyostation/",
    checkedAt: "2026年7月",
  },
  {
    id: "library-order",
    category: "文化",
    text: "図書館の本の背にある数字は、似たテーマの本を近くに並べるための手がかりです。",
    question: "本屋や図書館で、最初に見る棚は？",
    source: "国立国会図書館",
    url: "https://www.ndl.go.jp/jp/data/catstandards/classification_subject/ndlc.html",
    checkedAt: "2026年7月",
  },
  {
    id: "cloud-weight",
    category: "科学",
    text: "雲は軽く見えますが、小さな水滴が集まってできています。",
    question: "空を見ていて、何に見えた雲があった？",
    source: "NOAA",
    url: "https://www.noaa.gov/jetstream/clouds",
    checkedAt: "2026年7月",
  },
  {
    id: "cat-whiskers",
    category: "動物",
    text: "猫のひげは、狭い場所や周りの動きを感じ取る助けになります。",
    question: "動物のすごい感覚で、ひとつ欲しいのは？",
    source: "Cornell Feline Health Center",
    url: "https://www.vet.cornell.edu/departments-centers-and-institutes/cornell-feline-health-center",
    checkedAt: "2026年7月",
  },
  {
    id: "bread-holes",
    category: "食べ物",
    text: "パンの中の穴は、酵母などが生地の中で作ったガスがふくらんだ跡です。",
    question: "焼きたてで食べたいパンは？",
    source: "American Chemical Society",
    url: "https://www.acs.org/education/whatischemistry/adventures-in-chemistry/experiments/yeast-air-balloons.html",
    checkedAt: "2026年7月",
  },
];
